name: app_environment
channels:
  - snowflake
  - nodefaults
dependencies:
  - python >= 3.8
  - streamlit
  - pandas
  - numpy
  - scipy  # ✅ Only if available in Snowflake Anaconda
  - snowflake-snowpark-python
