name: app_environment
channels:
  - snowflake
  - nodefaults
dependencies:
  - python = 3.11
  - pandas
  - numpy
  - scipy  # ✅ Only if available in Snowflake Anaconda
  - streamlit
  - snowflake-snowpark-python
